---
- debug: msg="START connection={{ ansible_connection }}/invalid_subset.yaml"

- name: test invalid subset (foobar)
  nxos_facts:
    gather_subset:
      - "foobar"
  register: result
  ignore_errors: true

- assert:
    that:
      # Failures shouldn't return changes
      - "result.changed == false"
      # It's a failure
      - "result.failed == true"
      # Sensible Failure message
      - "'Subset must be one of' in result.msg"

- debug: msg="END connection={{ ansible_connection }}/invalid_subset.yaml"
